name: npm-publish
on:
  push:
    branches: [ master ]
jobs:
  npm-publish:
    name: npm-publish
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Build the project
      run: npm run build
    - name: Run test just in case
      run: npm run test
    - name: Publish, if version has been updated
      uses: JS-DevTools/npm-publish@v1
      env:
        token: ${{ secrets.NPM_AUTH_TOKEN }}